export enum JobCategory {
  ELECTRICIAN = 'ELECTRICIAN',
  PLUMBER = 'PLUMBER',
  PAINTER = 'PAINTER',
  CARPENTER = 'CARPENTER',
  HVAC_TECHNICIAN = 'HVAC_TECHNICIAN',
  APPLIANCE_REPAIR = 'APPLIANCE_REPAIR',
  GENERAL_CONTRACTOR = 'GENERAL_CONTRACTOR',
  ARCHITECT = 'ARCHITECT',
  INTERIOR_DESIGNER = 'INTERIOR_DESIGNER',
  LANDSCAPER = 'LANDSCAPER',
  MASON = 'MASON',
  ROOFER = 'ROOFER',
  FLOORING_SPECIALIST = 'FLOORING_SPECIALIST',
  SECURITY_SYSTEM_INSTALLER = 'SECURITY_SYSTEM_INSTALLER',
  HOME_INSPECTOR = 'HOME_INSPECTOR',
  CLEANING_SERVICE = 'CLEANING_SERVICE',
  PEST_CONTROL = 'PEST_CONTROL',
  POOL_MAINTENANCE = 'POOL_MAINTENANCE',
  SOLAR_INSTALLER = 'SOLAR_INSTALLER',
  SMART_HOME_TECHNICIAN = 'SMART_HOME_TECHNICIAN'
}

export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  WORKER = 'WORKER',
  ADMIN = 'ADMIN'
}

export enum JobStatus {
  PENDING = 'PENDING',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum ApplicationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED'
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  PENDING = 'PENDING'
}

export enum SubscriptionPlan {
  BASIC = 'BASIC',
  PRO = 'PRO',
  PREMIUM = 'PREMIUM'
}

export enum PurchaseStatus {
  COMPLETED = 'COMPLETED',
  PENDING = 'PENDING',
  FAILED = 'FAILED'
} 